import type { Alarm, AuditEntry, Batch, Equipment, Recipe, Role } from "./types";

export const users: { id: string; name: string; role: Role; shift: string; active: boolean }[] = [
  { id: "U-01", name: "สมชาย ผลิตดี", role: "operator", shift: "กะเช้า", active: true },
  { id: "U-02", name: "อารีย์ ตรวจสอบ", role: "supervisor", shift: "กะเช้า", active: true },
  { id: "U-03", name: "ณัฐพล วิศวกร", role: "engineer", shift: "ออฟฟิศ", active: true },
  { id: "U-04", name: "พิมพ์ใจ คุณภาพ", role: "qa", shift: "ออฟฟิศ", active: true },
  { id: "U-05", name: "ธนกร ดูแลระบบ", role: "admin", shift: "ออฟฟิศ", active: true },
  { id: "U-06", name: "วิชัย กะดึก", role: "operator", shift: "กะดึก", active: false },
];

export const recipes: Recipe[] = [
  {
    id: "R-1001",
    code: "RCP-CLN-01",
    name: "น้ำยาทำความสะอาดสูตรมาตรฐาน",
    product: "PRD-CLN-500",
    version: "v2.3",
    status: "approved",
    owner: "อารีย์ ตรวจสอบ",
    approvedBy: "พิมพ์ใจ คุณภาพ",
    updatedAt: "2026-08-28T09:15:00+07:00",
    batchSizeKg: 145,
    steps: [
      { no: 1, type: "dose", action: "เติมน้ำ RO", material: "RM-WATER", target: 100, unit: "kg", tolerance: 1, condition: "Valve-Water เปิด" },
      { no: 2, type: "dose", action: "เติมวัตถุดิบ A (Surfactant)", material: "RM-A-201", target: 25, unit: "kg", tolerance: 0.2, condition: "Operator ยืนยัน / สแกนบาร์โค้ด" },
      { no: 3, type: "mix", action: "ผสมรอบต่ำ", target: 5, unit: "นาที", speedRpm: 300, condition: "Mixer 300 RPM" },
      { no: 4, type: "dose", action: "เติมวัตถุดิบ B (Thickener)", material: "RM-B-114", target: 10, unit: "kg", tolerance: 0.1, condition: "Feeder-B ทำงาน" },
      { no: 5, type: "mix", action: "ผสมรอบสูง", target: 10, unit: "นาที", speedRpm: 800, condition: "Mixer 800 RPM" },
      { no: 6, type: "temp", action: "ตรวจอุณหภูมิก่อนจบ", target: 40, unit: "°C", tolerance: 2, condition: "เปิด Cooling หากเกิน 40°C" },
      { no: 7, type: "end", action: "จบ Batch และบันทึก Record", target: 0, unit: "-", condition: "บันทึก Batch Record อัตโนมัติ" },
    ],
  },
  {
    id: "R-1002",
    code: "RCP-PNT-04",
    name: "สีน้ำอะคริลิกภายใน เกรด A",
    product: "PRD-PNT-A20",
    version: "v1.7",
    status: "approved",
    owner: "ณัฐพล วิศวกร",
    approvedBy: "พิมพ์ใจ คุณภาพ",
    updatedAt: "2026-09-01T14:02:00+07:00",
    batchSizeKg: 210,
    steps: [
      { no: 1, type: "dose", action: "เติมน้ำ", material: "RM-WATER", target: 120, unit: "kg", tolerance: 1.5, condition: "Valve-Water เปิด" },
      { no: 2, type: "dose", action: "เติมผงไทเทเนียม", material: "RM-TIO2", target: 55, unit: "kg", tolerance: 0.5, condition: "Feeder-A ทำงาน" },
      { no: 3, type: "mix", action: "กระจายผง (Dispersion)", target: 12, unit: "นาที", speedRpm: 950, condition: "Mixer 950 RPM" },
      { no: 4, type: "dose", action: "เติมเรซิน", material: "RM-RES-77", target: 35, unit: "kg", tolerance: 0.3, condition: "Pump-2 ทำงาน" },
      { no: 5, type: "mix", action: "ผสมเข้ากัน", target: 8, unit: "นาที", speedRpm: 600, condition: "Mixer 600 RPM" },
      { no: 6, type: "end", action: "จบ Batch", target: 0, unit: "-", condition: "บันทึก Batch Record" },
    ],
  },
  {
    id: "R-1003",
    code: "RCP-FOD-09",
    name: "ซอสปรุงรสเข้มข้น",
    product: "PRD-FOD-SC1",
    version: "v0.9",
    status: "pending",
    owner: "อารีย์ ตรวจสอบ",
    updatedAt: "2026-09-05T11:40:00+07:00",
    batchSizeKg: 90,
    steps: [
      { no: 1, type: "dose", action: "เติมน้ำอุ่น", material: "RM-WATER", target: 60, unit: "kg", tolerance: 0.8, condition: "Valve-Water เปิด" },
      { no: 2, type: "dose", action: "เติมเกลือ", material: "RM-SALT", target: 8, unit: "kg", tolerance: 0.1, condition: "Operator ยืนยัน" },
      { no: 3, type: "mix", action: "กวนละลาย", target: 6, unit: "นาที", speedRpm: 250, condition: "Mixer 250 RPM" },
      { no: 4, type: "temp", action: "อุ่นถึงอุณหภูมิเป้าหมาย", target: 65, unit: "°C", tolerance: 2, condition: "Heating Jacket เปิด" },
      { no: 5, type: "end", action: "จบ Batch", target: 0, unit: "-", condition: "บันทึก Batch Record" },
    ],
  },
  {
    id: "R-1004",
    code: "RCP-CLN-02",
    name: "น้ำยาทำความสะอาดสูตรเข้มข้น (เก่า)",
    product: "PRD-CLN-900",
    version: "v1.2",
    status: "archived",
    owner: "ธนกร ดูแลระบบ",
    approvedBy: "พิมพ์ใจ คุณภาพ",
    updatedAt: "2026-05-19T08:00:00+07:00",
    batchSizeKg: 120,
    steps: [
      { no: 1, type: "dose", action: "เติมน้ำ", material: "RM-WATER", target: 90, unit: "kg", tolerance: 1, condition: "Valve-Water เปิด" },
      { no: 2, type: "dose", action: "เติมด่าง", material: "RM-ALK", target: 30, unit: "kg", tolerance: 0.4, condition: "Pump-1 ทำงาน" },
      { no: 3, type: "end", action: "จบ Batch", target: 0, unit: "-", condition: "บันทึก Batch Record" },
    ],
  },
];

export const historyBatches: Batch[] = [
  {
    id: "B-2401",
    batchNo: "BX-260906-01",
    lot: "LOT-260906-A",
    recipeId: "R-1001",
    recipeCode: "RCP-CLN-01",
    recipeVersion: "v2.3",
    product: "PRD-CLN-500",
    operator: "สมชาย ผลิตดี",
    status: "completed",
    createdAt: "2026-09-06T08:00:00+07:00",
    startedAt: "2026-09-06T08:05:00+07:00",
    endedAt: "2026-09-06T08:41:00+07:00",
    currentStep: 7,
    steps: [
      { no: 1, action: "เติมน้ำ RO", type: "dose", target: 100, unit: "kg", tolerance: 1, actual: 100.4, progress: 1, status: "done" },
      { no: 2, action: "เติมวัตถุดิบ A (Surfactant)", type: "dose", target: 25, unit: "kg", tolerance: 0.2, actual: 24.93, progress: 1, status: "done" },
      { no: 3, action: "ผสมรอบต่ำ", type: "mix", target: 5, unit: "นาที", actual: 5, progress: 1, status: "done" },
      { no: 4, action: "เติมวัตถุดิบ B (Thickener)", type: "dose", target: 10, unit: "kg", tolerance: 0.1, actual: 10.05, progress: 1, status: "done" },
      { no: 5, action: "ผสมรอบสูง", type: "mix", target: 10, unit: "นาที", actual: 10, progress: 1, status: "done" },
      { no: 6, action: "ตรวจอุณหภูมิก่อนจบ", type: "temp", target: 40, unit: "°C", tolerance: 2, actual: 38.6, progress: 1, status: "done" },
      { no: 7, action: "จบ Batch และบันทึก Record", type: "end", target: 0, unit: "-", actual: 0, progress: 1, status: "done" },
    ],
  },
  {
    id: "B-2402",
    batchNo: "BX-260906-02",
    lot: "LOT-260906-B",
    recipeId: "R-1002",
    recipeCode: "RCP-PNT-04",
    recipeVersion: "v1.7",
    product: "PRD-PNT-A20",
    operator: "วิชัย กะดึก",
    status: "aborted",
    createdAt: "2026-09-06T13:00:00+07:00",
    startedAt: "2026-09-06T13:10:00+07:00",
    endedAt: "2026-09-06T13:26:00+07:00",
    currentStep: 3,
    abortReason: "Motor Fault ที่ Mixer M-01 ระหว่างขั้นตอนกระจายผง",
    steps: [
      { no: 1, action: "เติมน้ำ", type: "dose", target: 120, unit: "kg", tolerance: 1.5, actual: 119.6, progress: 1, status: "done" },
      { no: 2, action: "เติมผงไทเทเนียม", type: "dose", target: 55, unit: "kg", tolerance: 0.5, actual: 55.8, progress: 1, status: "deviated" },
      { no: 3, action: "กระจายผง (Dispersion)", type: "mix", target: 12, unit: "นาที", actual: 4.2, progress: 0.35, status: "deviated" },
      { no: 4, action: "เติมเรซิน", type: "dose", target: 35, unit: "kg", tolerance: 0.3, actual: 0, progress: 0, status: "waiting" },
      { no: 5, action: "ผสมเข้ากัน", type: "mix", target: 8, unit: "นาที", actual: 0, progress: 0, status: "waiting" },
      { no: 6, action: "จบ Batch", type: "end", target: 0, unit: "-", actual: 0, progress: 0, status: "waiting" },
    ],
  },
  {
    id: "B-2403",
    batchNo: "BX-260907-01",
    lot: "LOT-260907-A",
    recipeId: "R-1001",
    recipeCode: "RCP-CLN-01",
    recipeVersion: "v2.3",
    product: "PRD-CLN-500",
    operator: "สมชาย ผลิตดี",
    status: "completed",
    createdAt: "2026-09-07T07:50:00+07:00",
    startedAt: "2026-09-07T08:00:00+07:00",
    endedAt: "2026-09-07T08:37:00+07:00",
    currentStep: 7,
    steps: [
      { no: 1, action: "เติมน้ำ RO", type: "dose", target: 100, unit: "kg", tolerance: 1, actual: 99.8, progress: 1, status: "done" },
      { no: 2, action: "เติมวัตถุดิบ A (Surfactant)", type: "dose", target: 25, unit: "kg", tolerance: 0.2, actual: 25.06, progress: 1, status: "done" },
      { no: 3, action: "ผสมรอบต่ำ", type: "mix", target: 5, unit: "นาที", actual: 5, progress: 1, status: "done" },
      { no: 4, action: "เติมวัตถุดิบ B (Thickener)", type: "dose", target: 10, unit: "kg", tolerance: 0.1, actual: 9.97, progress: 1, status: "done" },
      { no: 5, action: "ผสมรอบสูง", type: "mix", target: 10, unit: "นาที", actual: 10, progress: 1, status: "done" },
      { no: 6, action: "ตรวจอุณหภูมิก่อนจบ", type: "temp", target: 40, unit: "°C", tolerance: 2, actual: 39.4, progress: 1, status: "done" },
      { no: 7, action: "จบ Batch และบันทึก Record", type: "end", target: 0, unit: "-", actual: 0, progress: 1, status: "done" },
    ],
  },
];

export const seedAlarms: Alarm[] = [
  {
    id: "A-9001",
    at: "2026-09-06T13:24:10+07:00",
    level: "critical",
    source: "Mixer M-01",
    message: "Motor Fault — ตรวจพบกระแสเกินพิกัด ระบบหยุด Batch อัตโนมัติ",
    batchNo: "BX-260906-02",
    ackBy: "ณัฐพล วิศวกร",
    ackAt: "2026-09-06T13:31:00+07:00",
  },
  {
    id: "A-9002",
    at: "2026-09-06T13:18:44+07:00",
    level: "warning",
    source: "Load Cell LC-02",
    message: "น้ำหนักวัตถุดิบเกิน Tolerance (+0.80 kg จากเป้าหมาย 55.0 kg)",
    batchNo: "BX-260906-02",
    ackBy: "วิชัย กะดึก",
    ackAt: "2026-09-06T13:20:00+07:00",
  },
  {
    id: "A-9003",
    at: "2026-09-07T08:12:02+07:00",
    level: "info",
    source: "ระบบ",
    message: "เริ่ม Batch BX-260907-01 ด้วยสูตร RCP-CLN-01 v2.3",
    batchNo: "BX-260907-01",
    ackBy: "สมชาย ผลิตดี",
    ackAt: "2026-09-07T08:12:30+07:00",
  },
];

export const seedAudit: AuditEntry[] = [
  { id: "T-01", at: "2026-09-05T11:40:00+07:00", user: "อารีย์ ตรวจสอบ", role: "supervisor", action: "แก้ไขสูตร", detail: "RCP-FOD-09 ปรับ Tolerance ขั้นตอนเติมเกลือ เป็น ±0.1 kg" },
  { id: "T-02", at: "2026-09-06T13:26:00+07:00", user: "วิชัย กะดึก", role: "operator", action: "ยกเลิก Batch", detail: "BX-260906-02 เหตุผล: Motor Fault ที่ Mixer M-01" },
  { id: "T-03", at: "2026-09-01T14:02:00+07:00", user: "พิมพ์ใจ คุณภาพ", role: "qa", action: "อนุมัติสูตร", detail: "RCP-PNT-04 v1.7 ผ่านการอนุมัติ" },
  { id: "T-04", at: "2026-08-28T09:20:00+07:00", user: "ณัฐพล วิศวกร", role: "engineer", action: "Calibration", detail: "สอบเทียบ Load Cell LC-01 ค่าเบี่ยงเบน 0.02%" },
];

export const equipmentSeed: Equipment[] = [
  { id: "M-01", name: "Mixer หลัก", kind: "Mixer / VFD", status: "ok", value: 0, unit: "RPM" },
  { id: "LC-01", name: "Load Cell ถังผสม", kind: "Load Cell", status: "ok", value: 0, unit: "kg" },
  { id: "TT-01", name: "เซนเซอร์อุณหภูมิ", kind: "Temperature", status: "ok", value: 31.5, unit: "°C" },
  { id: "FT-01", name: "Flow Meter น้ำ", kind: "Flow Meter", status: "ok", value: 0, unit: "L/min" },
  { id: "LV-01", name: "วาล์วน้ำ", kind: "Valve", status: "ok", value: 0, unit: "%" },
  { id: "PP-02", name: "ปั๊มเรซิน", kind: "Pump", status: "ok", value: 0, unit: "%" },
];
