/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlarmsRouteImport } from './routes/alarms'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SpecificGravityRouteImport } from './routes/specific-gravity'
import { Route as UsersRouteImport } from './routes/users'
import { Route as BatchesIndexRouteImport } from './routes/batches.index'
import { Route as BatchesBatchIdRouteImport } from './routes/batches.$batchId'
import { Route as RecipesIndexRouteImport } from './routes/recipes.index'
import { Route as RecipesRecipeIdRouteImport } from './routes/recipes.$recipeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlarmsRoute = AlarmsRouteImport.update({
  id: '/alarms',
  path: '/alarms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecificGravityRoute = SpecificGravityRouteImport.update({
  id: '/specific-gravity',
  path: '/specific-gravity',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchesIndexRoute = BatchesIndexRouteImport.update({
  id: '/batches/',
  path: '/batches/',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchesBatchIdRoute = BatchesBatchIdRouteImport.update({
  id: '/batches/$batchId',
  path: '/batches/$batchId',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIndexRoute = RecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRecipeIdRoute = RecipesRecipeIdRouteImport.update({
  id: '/recipes/$recipeId',
  path: '/recipes/$recipeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alarms': typeof AlarmsRoute
  '/audit': typeof AuditRoute
  '/reports': typeof ReportsRoute
  '/specific-gravity': typeof SpecificGravityRoute
  '/users': typeof UsersRoute
  '/batches/$batchId': typeof BatchesBatchIdRoute
  '/recipes/$recipeId': typeof RecipesRecipeIdRoute
  '/batches/': typeof BatchesIndexRoute
  '/recipes/': typeof RecipesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alarms': typeof AlarmsRoute
  '/audit': typeof AuditRoute
  '/reports': typeof ReportsRoute
  '/specific-gravity': typeof SpecificGravityRoute
  '/users': typeof UsersRoute
  '/batches/$batchId': typeof BatchesBatchIdRoute
  '/recipes/$recipeId': typeof RecipesRecipeIdRoute
  '/batches': typeof BatchesIndexRoute
  '/recipes': typeof RecipesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alarms': typeof AlarmsRoute
  '/audit': typeof AuditRoute
  '/reports': typeof ReportsRoute
  '/specific-gravity': typeof SpecificGravityRoute
  '/users': typeof UsersRoute
  '/batches/$batchId': typeof BatchesBatchIdRoute
  '/recipes/$recipeId': typeof RecipesRecipeIdRoute
  '/batches/': typeof BatchesIndexRoute
  '/recipes/': typeof RecipesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alarms'
    | '/audit'
    | '/reports'
    | '/specific-gravity'
    | '/users'
    | '/batches/$batchId'
    | '/recipes/$recipeId'
    | '/batches/'
    | '/recipes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alarms'
    | '/audit'
    | '/reports'
    | '/specific-gravity'
    | '/users'
    | '/batches/$batchId'
    | '/recipes/$recipeId'
    | '/batches'
    | '/recipes'
  id:
    | '__root__'
    | '/'
    | '/alarms'
    | '/audit'
    | '/reports'
    | '/specific-gravity'
    | '/users'
    | '/batches/$batchId'
    | '/recipes/$recipeId'
    | '/batches/'
    | '/recipes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlarmsRoute: typeof AlarmsRoute
  AuditRoute: typeof AuditRoute
  ReportsRoute: typeof ReportsRoute
  SpecificGravityRoute: typeof SpecificGravityRoute
  UsersRoute: typeof UsersRoute
  BatchesBatchIdRoute: typeof BatchesBatchIdRoute
  RecipesRecipeIdRoute: typeof RecipesRecipeIdRoute
  BatchesIndexRoute: typeof BatchesIndexRoute
  RecipesIndexRoute: typeof RecipesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alarms': {
      id: '/alarms'
      path: '/alarms'
      fullPath: '/alarms'
      preLoaderRoute: typeof AlarmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specific-gravity': {
      id: '/specific-gravity'
      path: '/specific-gravity'
      fullPath: '/specific-gravity'
      preLoaderRoute: typeof SpecificGravityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batches/': {
      id: '/batches/'
      path: '/batches'
      fullPath: '/batches/'
      preLoaderRoute: typeof BatchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batches/$batchId': {
      id: '/batches/$batchId'
      path: '/batches/$batchId'
      fullPath: '/batches/$batchId'
      preLoaderRoute: typeof BatchesBatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/': {
      id: '/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof RecipesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$recipeId': {
      id: '/recipes/$recipeId'
      path: '/recipes/$recipeId'
      fullPath: '/recipes/$recipeId'
      preLoaderRoute: typeof RecipesRecipeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlarmsRoute: AlarmsRoute,
  AuditRoute: AuditRoute,
  ReportsRoute: ReportsRoute,
  SpecificGravityRoute: SpecificGravityRoute,
  UsersRoute: UsersRoute,
  BatchesBatchIdRoute: BatchesBatchIdRoute,
  RecipesRecipeIdRoute: RecipesRecipeIdRoute,
  BatchesIndexRoute: BatchesIndexRoute,
  RecipesIndexRoute: RecipesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
